FROM public.ecr.aws/lambda/provided:al2

# Repo of fluent-bit
COPY fluent-bit.repo /etc/yum.repos.d/fluent-bit.repo

# Update packages and install fluent-bit
RUN ["yum", "update",  "-y"]
RUN ["yum", "install", "fluent-bit", "-y"]

# Script to start fluent-bit and lambda
COPY lambda-startup.sh .

EXPOSE 2020

ENTRYPOINT ["/bin/sh", "lambda-startup.sh"]